# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deep Dungeon Compendium
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A compilation of information regarding the Palace of the Dead and Heaven on
  High deep dungeons in Final Fantasy XIV. Intended for use as a guide to both
  groups and solo players looking to clear on any job.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  djcooke
ga_measurement_id: G-9Y46PNPE95

collections:
  potd_floorsets:
    output: true
    max_floor: 200
  potd_001_enemies:
    output: false
  potd_011_enemies:
    output: false
  potd_021_enemies:
    output: false
  potd_031_enemies:
    output: false
  potd_041_enemies:
    output: false
  potd_051_enemies:
    output: false
  potd_061_enemies:
    output: false
  potd_071_enemies:
    output: false
  potd_081_enemies:
    output: false
  potd_091_enemies:
    output: false
  potd_101_enemies:
    output: false
  potd_111_enemies:
    output: false
  potd_121_enemies:
    output: false
  potd_131_enemies:
    output: false
  potd_141_enemies:
    output: false
  potd_151_enemies:
    output: false
  potd_161_enemies:
    output: false
  potd_171_enemies:
    output: false
  potd_181_enemies:
    output: false
  potd_191_enemies:
    output: false
  hoh_floorsets:
    output: true
    max_floor: 100
  hoh_001_enemies:
    output: false
  hoh_011_enemies:
    output: false
  hoh_021_enemies:
    output: false
  hoh_031_enemies:
    output: false
  hoh_041_enemies:
    output: false
  hoh_051_enemies:
    output: false
  hoh_061_enemies:
    output: false
  hoh_071_enemies:
    output: false
  hoh_081_enemies:
    output: false
  hoh_091_enemies:
    output: false
  eo_floorsets:
    output: true
    max_floor: 100
  eo_001_enemies:
    output: false
  eo_011_enemies:
    output: false
  eo_021_enemies:
    output: false
  eo_031_enemies:
    output: false
  eo_041_enemies:
    output: false
  eo_051_enemies:
    output: false

defaults:
  - scope:
      path: ""
      type: "potd_floorsets"
    values:
      layout: "floorset"
  - scope:
      path: ""
      type: "hoh_floorsets"
    values:
      layout: "floorset"
  - scope:
      path: ""
      type: "eo_floorsets"
    values:
      layout: "floorset"

exclude:
  - templates

# Build settings
theme: null
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
